### ISSUE TITLE
Suborganizations should be shown the same way as in search results

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#137]
- in Excel export

**Comment by tjnurmin** [comment]
Organisaatiotietoa ei tässä roolimuodossa voi hyödyntä lajittelussa tms. eli tarvittaisiin uudet kentät/sarakkeet piiriä ja seuraa varten sekä pitkään että perus Excel-vientiin.

**Comment by tjnurmin** [comment]
- Ainut mahdollisuus tähän on, että valitaan tietokannasta ensimmäinen seura ja sen piiri, joka ko. henkilön tiedoista löytyy.

**Comment by rrimpila** [comment]
Vaihdettu kysely aliorganisaatioille näyttämään vain yksi piiri/seura ja sen piiri kutakin riviä kohden eri sarakkeille jaettuna

**Comment by tjnurmin** [comment]
...but all groups should also be shown still. Apparently nothing to be done about the char count limitation in groups+roles list?

**Comment by rrimpila** [comment]
character count limitation is imposed by mysql, to get around it, the query would need to be restructured (into something most likely quite a lot more processing intensive)

All groups readded
