### ISSUE TITLE
Contacts should be joined to groups the same way as members

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#143]
- current long list is not very user friendly

**Comment by rrimpila** [comment]
Long list in a dropdown to add groups is also a bit difficult to handle, especially when adding multiple groups. Added currently chosen groups for the contact in a list view as well, for easier checking, and kept checkboxes for quick updating. Discuss with client if they really want the dropdown method for adding groups

**Comment by tjnurmin** [comment]
Approved by client, no further changes necessary.
