### ISSUE TITLE
Area should be able to add / remove persons to groups / roles

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#150]
- i.e. $_SESSION[$ip]['viewLevel'] = 1

**Comment by rrimpila** [comment]
Added the group control forms in member listing and search listing for areas

**Comment by tjnurmin** [comment]
Remove from groups should be barred from 2nd level views.

**Comment by rrimpila** [comment]
Barred lower level views from removing from groups

**Comment by tjnurmin** [comment]
Comment from client: 2nd level must be able to add / remove to groups that are visible to 2nd level.

**Comment by rrimpila** [comment]
Every level has now access to adding and removing to groups, but they are only allowed groups  visible to their level

**Comment by rrimpila** [comment]
Needed to allow views access to interface, can this cause trouble elsewhere?
