### ISSUE TITLE
Make possible to give view admin rights to individual member

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#159]
- login run in user.class.php:210 (trivial change)
- $memberTable gets set in do_admin_index.inc.php
- admin rights to view given for members in admin/setView.php, this is called via search and members.inc.php
- client has, however, different logic for inserting members into view
- table structure for ordinary clients (see admin + readonly fields):
  
  CREATE TABLE `views_members` (
  `link_view` mediumint(8) unsigned NOT NULL,
  `link_member` mediumint(8) unsigned default NULL,
  `link_application` mediumint(8) unsigned default NULL,
  `admin` tinyint(1) unsigned NOT NULL default '0',
  `readonly` tinyint(1) unsigned NOT NULL default '0'
  ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci;

**Comment by rrimpila** [comment]
Admin rights can now be given to members in members view tab 2. It has a form for adding a view, and lists the views to which rights have been given. The texts should probably be more clear on the function of the form, though
