### ISSUE TITLE
Creating msg body should be extracted from send-method

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#168]
- in Emailer.class.php

**Comment by rrimpila** [comment]
Class update to with a function to update message body, one function to update attachments, and finally send to send the message. This needs to be tested with invoicing, works with flomembers sending email.

**Comment by rrimpila** [comment]
And also fixed arrayofsuccesses to update within the sending loop, in case loop gets interrupted, so that the end report of reached addresses is more accurate
