### ISSUE TITLE
Groups should be shown when viewing applications

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#187]
- requested 8 Aug 2012
- if application is linked to groups, these groups should be listed

**Comment by rrimpila** [comment]
Application edit now displays group memberships with links to the application in a list. List is not displayed if there are no groups. 

The member link in memberships is irrelevent in these cases?

**Comment by tjnurmin** [comment]
Yes, link_member should not exist at all before applicant becomes a member.
