### ISSUE TITLE
Removing registration

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#197]
Miksi tapahtumakalenterissa ei pääse kyseisen päivän tapahtumaan enää käsiksi? Peruuttaminen ei onnistu, kun Tapahtuma sulkeutuu. Sen pitäisi olla auki tapahtumaan asti tai sitten ilmoittautumisvahvistuksessa pitäisi olla viimeinen peruutusajankohta mainittuna.

**Comment by tjnurmin** [comment]
Onkohan tämä uudessa versiossa enää näin?

**Comment by aleksitaipale** [comment]
Koitin tätä siten, että loin tapahtuman `demo@flomembers.com`-tunnuksilla. Otin sitten tapahtumalinkin ja avasin sen "Lasse Björginä" sisään loganneena. Rekisteröityminen onnistui niin kuin pitikin. Kävin tämän jälkeen vaihtamassa tietokannasta rekisteröinnin deadlinen eiliseksi ja tapahtuman päivämäärän täksi päiväksi. Tällöin "Lassen" tapahtumakalenterissa ei enää näy tapahtuman vieressä `Rekisteröidy`-linkkiä. Koitin peruuttaa ilmoittautumiseni sähköpostiin tulleen peruutuslinkin avulla ja se onnistui hyvin. Jos siis käsitän oikein, niin ongelmaa ei ole koska peruminen onnistuu myös tapahtumapäivänä?

**Comment by tjnurmin** [comment]
Muistaakseni tapahtumaan voi ilmoittautua myös suoraan FloMembersin sisällä, kun jäsen kirjautuu. Testaatkö vielä, miten peruminen tapahtuu siellä.

**Comment by aleksitaipale** [comment]
FloMembersin kautta voi tosiaan ilmoittautua, mutta ei perua ilmoittautumistaan. Se onnistuu tällä hetkellä ilmeisesti ainoastaan sähköpostiin saadun linkin kautta.
