### ISSUE TITLE
Mentoring: several mentors appear to be able to accept the same case

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#202]
See

```
SELECT * FROM `mtr_cases_mentors`
WHERE `link_caseid` =72
```

contents/user/mentoringCases.php

**Comment by rrimpila** [comment]
The query only checked that the current mentor had not accepted the case. Now altered to also check for other accepted mentors. Also added check to the commit, in case two mentors have the page open at the same time. Error texts now 'Sorry, the mentoring position is no longer available.' heading, and 'A mentor has already accepted the invitation.' body.
