### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#225]
- käyttöohje on osoitteessa https://docs.google.com/document/d/1o9O2BwnsW80419bgfG5zeOKEwbkOnCkxD06_wAVLY-A/edit
- ilmeisesti käyttöohjeen tulostamisessa PDF:ksi on ollut Windowsissa ongelmia; tämä pitäisi testata
- entä voiko Google-taulukon (toisen GoogleDocin) integroida (embed) tekstidokkariin

**Comment by jokiilk** [comment]
En ainakaan keksi mitään ratkaisua tuohon taulukon tekstitiedostoon upottamiseen. Kuvaajaksi piirretyn datan saa kyllä spreadsheetista linkattua dociin. 

Selvittelen windows-homman kun pääsen kotiin windowsin ääreen.

**Comment by tjnurmin** [comment]
Epäilinkin ettei GoogleDocs tue taulukon upottamista, siinä olisi omat 
haasteensa.

**Comment by jokiilk** [comment]
Nyt on testattu windows-koneella. PDF:n lataus toimi niin Chromella, FF:lla kuin Exploderillakin.
