### ISSUE TITLE
Link to "Intranet" in discussion forum

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#233]
- client wants to change text in header.tpl - rather than hardcoding this, translation files etc might be a better option - where does Phorum keep these?

**Comment by rrimpila** [comment]
phorum/include/lang/finnish.php has an array for the translations in the form key => text and the translation is utilized in the templates appartently using {LANG->key}.

Other option would be using modules, in mods folder. They can provide templates with variables to display, but this might be too complex for just a link. External_authentication module has flo-specific code.

**Comment by rrimpila** [comment]
added to translation file
