### ISSUE TITLE
Hide basket in ckFinder

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#235]
- ckFinder shows "Basket" by default - should be able to disable

**Comment by rrimpila** [comment]
Basket is now hidden. I could not find a way to set it on php configuration, it is now done via js.

Basket is a virtual folder for performing operations on multiple files at once. Basket is unique for a user (session-based, apparently), and moving files to basket does not actually affect the files in anyway (before the user performs operations on the chosen files).

**Comment by tjnurmin** [comment]
- let's check with the client first what to do

**Comment by tjnurmin** [comment]
- left basket into use
