### ISSUE TITLE
Db error

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#247]
```
/flomembers/demo/?action=roles&do=insert
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'visible_to_views' cannot be null
23000
/home/webadmin/shared_code/classes/form_generator.class.php
1638
    #0 /home/webadmin/shared_code/classes/form_generator.class.php(1638): PDO->query('INSERT INTO `ro...')
    #1 /home/webadmin/shared_code/classes/form_generator.class.php(1015): form_generator->runSQL('INSERT INTO `ro...', true)
```

**Comment by rrimpila** [comment]
Ajaxform clearform sets select to empty even if there was no empty option present. So user was able to add a role, get the select emptied, and try adding another group. Set select to be required to avoid this possiblity. Other option would be to replace the clearform in ajaxform with only resetform, but this would affect more forms, and would need to be checked not to cause problems.
