### ISSUE TITLE
grantViewAdminRights should be able to remove rights too

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#250]

**Comment by rrimpila** [comment]
Probably needed to change setView to update all the rights according to the selection, and removing the grantviewadminrights column from the table

**Comment by rrimpila** [comment]
ALTER TABLE `views_members` ADD PRIMARY KEY ( `link_view` , `link_member` , `link_application` )

**Comment by rrimpila** [comment]
now setview can update and remove rights for single person, search results work as previously
