### ISSUE TITLE
Local backup for jQuery Core

### ISSUE THREAD

**Issue by rrimpila** [tjnurmin/FloMembers#271]
System loads jQuery from Google server. In case Google service is unavailable, there could be a local backup that is loaded in case the file is not received:

http://stackoverflow.com/questions/1014203/best-way-to-use-googles-hosted-jquery-but-fall-back-to-my-hosted-library-on-go

**Comment by tjnurmin** [comment]
Tämän voisi toteuttaa Yii-versioon. Se lataa nyt paikallisen version (1.8.3):

yii_flomembers/assets/e40e1297/jquery.min.js

Googlelta https:n yli ladattava saisi tietty olla oletusarvoinen.
