### ISSUE TITLE
Event registration into group

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#306]
a. Anna uuden ryhmän nimi tai valitse olemassa olevista

b. Jos tekee uuden ryhmän, luodaan tämä

c. liitetään jäsenet ko. ryhmään siten, ettei tule duplikaatteja

INSERT INTO groups_members ...
SELECT link_member FROM event_registrations
INNER JOIN events ON link_event = events.id
WHERE link_member IS NOT NULL AND link_event = $x

**Comment by jlouhio** [comment]
Nyt voi luoda ryhmän tapahtuman osallistujista. Kun ryhmää tarkastellaan tapahtuman kautta, uudet tapahtumaan ilmoittautuneet lisätään ryhmään. Muutoin tapahtumaan ilmoittautuneita ei automaattisesti lisätä ryhmään heti tapahtumaan ilmoittautumisen yhteydessä. Sekin on toteutettavissa, jos halutaan.

**Comment by tjnurmin** [comment]
Ryhmä pitää luoda vain, jos siihen on tulossa henkilöitä. Muuten pitää pysäyttää redierct ja ilmoittaa että liitettäviä ei ole.
