### ISSUE TITLE
New version does not generate reports for bankdata import

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#320]
Vain pääkäyttäjä saa viestin ja se on tyhjä:

"Bankdata Distribution: 13/2013

Tilisiirrot"

**Comment by jlouhio** [comment]
Puuttui parametri funktiolta, jota käytetään rivillä 472 ja joka määritelty rivillä 486. 

$generatedReport = $this->generateClientReport($currentClient);

Määritellyssä funktiossa oli tarkistus 'isset', joka piilotti tämän virheen puuttuvasta parametristä.
