### ISSUE TITLE
Add validation for Maventa code to ensure they're in right format

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#323]

**Comment by tjnurmin** [comment]
Voisi kirjoittaa JS regexin joka katsoo että Maventa API key on oikean mittainen ja ehkä oikeassa formaatissa. Webapps_flo -kannasta löytyy meidän key. Tätä tarvitaan FloMembersin Settings-kohdassa.

**Comment by tjnurmin** [comment]
Tai sitten HTML5 saattaa tarjota jotain sopivaa jo valmiiksi.

**Comment by rrimpila** [comment]
HTML5 tarjoaisi pattern-attribuutin inputeille, johon voidaan kirjoittaa regex pattern tarkastamaan oikea formaatti. Tämä tarkastus ei kuitenkaan tuota näkyviä tuloksia järjestelmässä, oletettavasti tyylit piilottavat selaimen ulkonäön muutokset, ja javascript-validointi ja -lähetys kiertävät lähettämisen.

Tarkastus on nyt siis lisätty validate-pluginin säännöksi, joka tehdään classin maventa perusteella. Tämä class on lisätty sekä apin avaimelle, että tunnukselle, jotka ainakin meidän tiedoissamme näyttivät samalta formaatilta. Pattern on nyt /^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$/i, joka pakottaa väliviivat samoille asemille. Onko tietoa voiko tämä välistys vaihdella? Ainakin sekä tunnus, että avain olivat tätä muotoa. Jos halutaan tarkistus vain oikealle määrälle merkkejä, siinä toiminee /^[a-z0-9-]{36}$/i.

**Comment by tjnurmin** [comment]
Tämä riittää tällä erää, ilmeisesti välistys on aina sama.
