### ISSUE TITLE
If due date is null, will yield 1/1/1970 as due date

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#331]

**Comment by tjnurmin** [comment]
Tätä voisi selvitellä Maventan dokumentaation / henkilökunnan kanssa.

**Comment by rrimpila** [comment]
Ongelma oli date-funktiossa, jolla tehtiin oikeaa muotoa oleva päivämäärä. Tämä muodosti 1970 päivämäärän, kun duedate oli null. 

Nyt tässä on tarkistus, joka jättää päivämääräkentän arvoksi null, jos duedate on null. Maventan api kuitenkin vaatii oikean eräpäivän ja antaa virheilmoituksen väärästä formaatista.
