### ISSUE TITLE
When adding person to view, this connection duplicates

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#335]
Kun liitän jo rekisterissä olevan jäsenen jonkun paikallisseuran jäseneksi, hänen kohdallaan näkyy sen jälkeen pääseuran jäsenyys kaksinkertaisena.

**Comment by rrimpila** [comment]
Current code requires uniqueness constraint (primary key) on link_view, link_member, link_application, or otherwise updating the view rights will create a duplicate. In addition, adding the key will remove all the duplicates.

**Comment by tjnurmin** [comment]
Some clients were missing index; added it.

```
ALTER TABLE `views_members` ADD 
PRIMARY KEY  (`link_view`,`link_member`,`link_application`)
```
