### ISSUE TITLE
View cannot delete invoices created by itself

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#343]
- if simple and safe to fix, this would be useful to ML
- ping @virvea

**Comment by rrimpila** [comment]
Views are explicitly forbidden to delete anything else except from views_members. Other tables can be added to the check very simply, but doing only this would enable views to remove anything from the invoices.

Additionally there should be a check that the invoice is related to the view that is trying to delete it. This should be possible with a couple of lines of sql.

**Comment by tjnurmin** [comment]
As this seems pretty important, let's add this feature still.

**Comment by rrimpila** [comment]
Added logic interface to allow views to deleted invoices created by themselves and subviews, logic follows the one from removing from groups_members.

**Comment by tjnurmin** [comment]
Tested, seems to work as planned. ping @virvea
