### ISSUE TITLE
Sent messages could be shown in their entirety

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#58]
Should be possible to view each message in their entirety, so that they could also be copy pasted if need be.

**Comment by rrimpila** [comment]
Emails now displays view button to show the message in a readonly form. This form can be submitted to email sending. Email sending uses the subject and message in the message fields if available.

CKEditor automatically adds p tags to surround also plain text messages. Should these be eliminated, or automatically set the emailing to be as html?

**Comment by tjnurmin** [comment]
Automatic HTML might work better.

**Comment by rrimpila** [comment]
Set email to put html editor on automatically from copying sent email
