### ISSUE TITLE
SMS: message length could be checked

### ISSUE THREAD

**Issue by tjnurmin** [tjnurmin/FloMembers#8]

**Comment by rrimpila** [comment]
CardBoardFish promises to be able to part long messages into multiple, but that many phones can only handle three-part messages. 

Adding counter for mobile message field, and character limit of 459. Javascript add character limiting plugin, and maxlength attribute to each element with class mobilemessage, the other function call is to mimic the maxlength behaviour in browsers that might not support it

```
var maxChar = 459;    
$('.mobileMessage').attr("maxlength", maxChar).each(function (index, item) 
{
    item.onkeypress = function(event) {
        var k = event ? event.which : window.event.keyCode;
        if(this.value.length >= maxChar) if(k>46 && k<112 || k>123) return false;
    }
}).charCount({
    allowed: maxChar
});
```

Counter still needs styling.

**Comment by tjnurmin** [comment]
counterText: 'Characters left: ' does not seem to function; wanted to add explanation before counter

**Comment by jlouhio** [comment]
Fixed missing explanation text. With Opera fast-typing user can type more than set limit. But, there is at least css warning if this limit is exceeded, so not sure how big of a problem this is.
